//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace KDMYsoft.Web.Nhiber.Accounts_Users {
    
    
    /// <summary>
    /// Show 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Show {
        	protected global::System.Web.UI.WebControls.Label lblUserID;
	protected global::System.Web.UI.WebControls.Label lblUserName;
	protected global::System.Web.UI.WebControls.Label lblPassword;
	protected global::System.Web.UI.WebControls.Label lblTrueName;
	protected global::System.Web.UI.WebControls.Label lblSex;
	protected global::System.Web.UI.WebControls.Label lblPhone;
	protected global::System.Web.UI.WebControls.Label lblEmail;
	protected global::System.Web.UI.WebControls.Label lblEmployeeID;
	protected global::System.Web.UI.WebControls.Label lblDepartmentID;
	protected global::System.Web.UI.WebControls.Label lblActivity;
	protected global::System.Web.UI.WebControls.Label lblUserType;
	protected global::System.Web.UI.WebControls.Label lblStyle;


       
    }
}
